"""Capability-scoped repository ports for belief use cases."""

from contextlib import AbstractContextManager
from typing import Any, Protocol


class BeliefQueryRepository(Protocol):
    def list_beliefs(self, agent_id: str) -> list[Any]: ...
    def get_events_for_belief(self, belief_id: str, limit: int = 100) -> list[Any]: ...
    def list_proposals(self, agent_id: str) -> list[Any]: ...
    def get_conversation_somatic_state(self, conversation_id: str) -> dict[str, Any] | None: ...
    def get_belief(self, agent_id: str, belief_id: str | None = None) -> Any | None: ...


class BeliefProposalRepository(Protocol):
    def atomic(self) -> AbstractContextManager[None]: ...
    def get_proposal(self, proposal_id: str) -> Any | None: ...
    def list_proposals(self, agent_id: str) -> list[Any]: ...
    def list_beliefs(self, agent_id: str) -> list[Any]: ...
    def get_belief(self, agent_id: str, belief_id: str | None = None) -> Any | None: ...
    def update_proposal_status(self, proposal_id: str, status: str, rejection_rationale: str | None = None) -> None: ...
    def create_belief(self, **kwargs: Any) -> Any: ...
    def create_statement_version(self, **kwargs: Any) -> Any: ...
    def update_belief_statement(self, **kwargs: Any) -> None: ...
    def update_belief(self, **kwargs: Any) -> None: ...
    def update_belief_mass(self, belief_id: str, ontological_mass: float, touch_reinforced: bool = True) -> None: ...
    def insert_belief_event(self, **kwargs: Any) -> Any: ...


class BeliefMutationRepository(Protocol):
    def atomic(self) -> AbstractContextManager[None]: ...
    def get_belief(self, agent_id: str, belief_id: str | None = None) -> Any | None: ...
    def create_belief(self, **kwargs: Any) -> Any: ...
    def create_statement_version(self, **kwargs: Any) -> Any: ...
    def update_belief_details(self, **kwargs: Any) -> None: ...
    def insert_belief_event(self, **kwargs: Any) -> Any: ...
    def delete_belief(self, belief_id: str) -> None: ...


class BeliefVersionRepository(Protocol):
    def atomic(self) -> AbstractContextManager[None]: ...
    def list_beliefs(self, agent_id: str) -> list[Any]: ...
    def list_statement_versions(self, belief_id: str) -> list[Any]: ...
    def get_statement_version(self, belief_id: str, version: int) -> Any | None: ...
    def get_belief(self, agent_id: str, belief_id: str | None = None) -> Any | None: ...
    def update_belief_statement(self, **kwargs: Any) -> None: ...
    def update_belief_details(self, **kwargs: Any) -> None: ...
    def create_statement_version(self, **kwargs: Any) -> Any: ...
    def insert_belief_event(self, **kwargs: Any) -> Any: ...
