from backend.modules.background_tasks.actions.consolidate import ConsolidateAction
from backend.modules.background_tasks.actions.document_collision import DocumentCollisionAction
from backend.modules.background_tasks.actions.semantic_knot import SemanticKnotAction
from backend.modules.background_tasks.actions.summarize import SummarizeAction
from backend.modules.background_tasks.actions.title import GenerateTitleAction
