import { defaultSchema } from "rehype-sanitize"

/**
 * Strict sanitization schema extending GitHub markdown defaults.
 * Permits custom AAA tags (e.g. <mark>, <aaa-note>, <research-proposal>)
 * with specific safe attributes, while strictly stripping <script>, <iframe>,
 * and all inline event handlers (onerror, onload, onclick, etc.).
 */
export const aaaSanitizeSchema = {
  ...defaultSchema,
  tagNames: [
    ...(defaultSchema.tagNames || []),
    "mark",
    "aaa-note",
    "note-entanglement",
    "note_entanglement",
    "scar-fold",
    "scar_fold",
    "research-proposal",
    "objective",
    "rationale",
    "suggested_depth",
    "suggested-depth",
    "suggested_breadth",
    "suggested-breadth",
    "is_agonistic",
    "is-agonistic",
    "somatic-alert",
    "somatic_alert",
    "rupture_site",
    "rupture-site",
    "line_of_flight",
    "line-of-flight",
    "new_plateau",
    "new-plateau",
    "dream_trigger",
    "dream-trigger",
    "belief_nucleate",
    "belief-nucleate",
  ],
  attributes: {
    ...defaultSchema.attributes,
    "*": [
      ...((defaultSchema.attributes && defaultSchema.attributes["*"]) || []),
      "type",
      "status",
      "comment",
      "title",
      ["className", "note-highlight", "note-personal", "note-shared", "note-agent"],
      "id",
      "dataNoteId",
      "data-note-id",
      "dataNoteComment",
      "data-note-comment",
      "dataNoteVisibility",
      "data-note-visibility",
      "noteId",
      "note-id",
      "note_id",
    ],
    mark: [
      "id",
      "dataNoteId",
      "data-note-id",
      "dataNoteComment",
      "data-note-comment",
      "dataNoteVisibility",
      "data-note-visibility",
      "noteId",
      "note-id",
      "note_id",
      ["className", "note-highlight", "note-personal", "note-shared", "note-agent"],
    ],
    dream_trigger: ["reason"],
    "dream-trigger": ["reason"],
    belief_nucleate: [
      "confidence",
      "label",
      "rationale",
      "trigger",
      "scope",
      "temporalScope",
      "temporal_scope",
      "consequence",
      "evidenceQuote",
      "evidence_quote",
    ],
    "belief-nucleate": [
      "confidence",
      "label",
      "rationale",
      "trigger",
      "scope",
      "temporalScope",
      "temporal_scope",
      "consequence",
      "evidenceQuote",
      "evidence_quote",
    ],
    "aaa-note": [
      "id",
      "dataNoteId",
      "data-note-id",
      "dataNoteComment",
      "data-note-comment",
      "dataNoteVisibility",
      "data-note-visibility",
      "noteId",
      "note-id",
      "note_id",
      ["className", "note-highlight", "note-personal", "note-shared", "note-agent"],
    ],
    "note-entanglement": [
      "id",
      "dataNoteId",
      "data-note-id",
      "dataNoteComment",
      "data-note-comment",
      "dataNoteVisibility",
      "data-note-visibility",
      "noteId",
      "note-id",
      "note_id",
      ["className", "note-highlight", "note-personal", "note-shared", "note-agent"],
    ],
    "note_entanglement": [
      "id",
      "dataNoteId",
      "data-note-id",
      "dataNoteComment",
      "data-note-comment",
      "dataNoteVisibility",
      "data-note-visibility",
      "noteId",
      "note-id",
      "note_id",
      ["className", "note-highlight", "note-personal", "note-shared", "note-agent"],
    ],
    "research-proposal": [
      "proposalId",
      "proposal-id",
      "title",
      "description",
      "objective",
      "status",
      ["className", "note-highlight", "note-personal", "note-shared", "note-agent"],
    ],
    a: [
      ...((defaultSchema.attributes && defaultSchema.attributes["a"]) || []),
      "target",
      "rel",
    ],
  },
}
